### ISSUE TITLE
8.6 additional dependencies

### ISSUE THREAD

**Issue by MayaGans** [JohnCoene/javascript-for-r-comments#21]
> In htmlwidgets those additional dependencies can be specified via the dependencies argument in the htmlwidgets::createWidget function, or they can be appended to the output of that function.

```
# create gio object
g <- gio::gio(arcs)

is.null(g$dependencies)
```

I think it'd be nice to see the first option spelled out in code here as well too as that might address issue #19 ?

**Comment by MayaGans** [comment]
Closed because you do this the next sentence 🤦‍♀️

**Comment by JohnCoene** [comment]
Maybe but still, you posting that comment leads me to think that first paragraph could be reworded better.
