### ISSUE TITLE
7.4.2 R code not working?

### ISSUE THREAD

**Issue by MayaGans** [JohnCoene/javascript-for-r-comments#25]
After the JS code didn't work I replaced the geo function as per section 7.4.2 but this also isn't rendering anything with `gio(arcs)` [I should mention that running the code snippet `gio(message = "This required but not used")` was the last time I saw something rendered (and very frustrating I'm not seeing any messages in the console 😬 )

**Comment by JohnCoene** [comment]
Oh lord no, does the console show any error?

**Comment by MayaGans** [comment]
I think this is tied to #23 - we'll get to the bottom of this!

**Comment by MayaGans** [comment]
Closed - yay typos.
