### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by JohnCoene** [JohnCoene/javascript-for-r-comments#34]
@MayaGans, @fmmattioni, @swsoyee, @timelyportfolio

Thank you for taking the time to review the book; I know it takes some time.

Your feedback is incredibly valuable, I've reopened the project and will tackle all these issues over the next month or so. Feel free to keep opening issues here, it's always welcome.

Hopefully I can make the book public by the end of next month.

[Acknowledgement](https://book.javascript-for-r.com/index.html#acknowledgement)

**Comment by fmmattioni** [comment]
Dear @JohnCoene,

Thank you very much! And once again thank you for the opportunity to read this amazing book prior to its release. I am sorry for my delay in the other sections, but I will post more comments once I finish them.

Thanks for the amazing job!
Felipe

**Comment by JohnCoene** [comment]
I think I have managed to tackle many of the issues you all raised already, thanks again!

**Comment by MayaGans** [comment]
Thank you for this incredible resource @JohnCoene !!!
